import time
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://practice.automationtesting.in/")
time.sleep(1)
Shop = driver.find_element_by_css_selector("#menu-item-40 > a").click()
time.sleep(1)
driver.execute_script("window.scrollBy(0, 300);")
time.sleep(1)
Add_to_basket_1 = driver.find_element_by_xpath("//a[@data-product_id='182']").click()
time.sleep(1)
Busket = driver.find_element_by_class_name("wpmenucart-contents").click()
time.sleep(1)
Proceed_to_Checkout =WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CLASS_NAME, "checkout-button")))
Proceed_Checkout = Proceed_to_Checkout.click()
Wait_firstName = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.ID, "billing_first_name")))
First_name = Wait_firstName.send_keys("Valera")
Last_name = driver.find_element_by_id("billing_last_name").send_keys("Ivanov")
Email = driver.find_element_by_id("billing_email").send_keys("valera@mail.ru")
Phone = driver.find_element_by_id("billing_phone").send_keys("89132541235")
Countru = driver.find_element_by_class_name("select2-choice").click()
time.sleep(1)
Countru_input = driver.find_element_by_class_name("select2-input").send_keys("Russia")
time.sleep(1)
Countru_chose = driver.find_element_by_class_name("select2-match").click()
time.sleep(1)
Adress = driver.find_element_by_id("billing_address_1").send_keys("Domova")
Aparnament = driver.find_element_by_id("billing_address_2").send_keys("43")
City = driver.find_element_by_css_selector(".input-text#billing_city").send_keys("Moskow")
Counry = driver.find_element_by_css_selector(".input-text#billing_state").send_keys("Russia")
Zip = driver.find_element_by_css_selector(".input-text#billing_postcode").send_keys("1234567")
driver.execute_script("window.scrollBy(0, 600);")
time.sleep(3)
Payment_method_cheque = driver.find_element_by_id("payment_method_cheque").click()
time.sleep(3)
Place_order = driver.find_element_by_id("place_order").click()
Thank_you = WebDriverWait(driver, 10).until(EC.text_to_be_present_in_element((By.CSS_SELECTOR,".woocommerce .woocommerce-thankyou-order-received"),"Thank you. Your order has been received."))
Payment_Method = WebDriverWait(driver,10).until(EC.text_to_be_present_in_element((By.CSS_SELECTOR,".shop_table.order_details>tfoot>tr:nth-child(3)>td"), "Check Payments"))
time.sleep(1)
driver.quit()