import time
from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://practice.automationtesting.in/")
time.sleep(1)
Shop = driver.find_element_by_css_selector("#menu-item-40 > a").click()
time.sleep(1)
driver.execute_script("window.scrollBy(0, 300);")
time.sleep(1)
Add_to_basket_1 = driver.find_element_by_xpath("//a[@data-product_id='182']").click()
time.sleep(1)
Add_to_basket_2 = driver.find_element_by_xpath("//a[@data-product_id='180']").click()
time.sleep(1)
Busket = driver.find_element_by_class_name("wpmenucart-contents").click()
time.sleep(1)
Delete_to_basket_1 = driver.find_element_by_xpath("//a[@data-product_id='182']").click()
time.sleep(2)
Undo = driver.find_element_by_link_text("Undo?").click()
time.sleep(3)
Quantity = driver.find_element_by_css_selector(".quantity:nth-child(1)>input")
Clear_Quantity = Quantity.clear()
Add_Quantity = Quantity.send_keys("3")
time.sleep(1)
Update_Basket = driver.find_element_by_xpath("//input[@value='Update Basket']").click()
Quantity_JsData = Quantity.get_attribute("value")
assert Quantity_JsData =="3"
time.sleep(3)
Apply_Coupon = driver.find_element_by_xpath("//input[@value='Apply Coupon']").click()
time.sleep(3)
Error_Coupon = driver.find_element_by_class_name("woocommerce-error")
Error_Coupon_text = Error_Coupon.text
assert Error_Coupon_text == "Please enter a coupon code."
time.sleep(1)
driver.quit()