import time
from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://practice.automationtesting.in/")
time.sleep(1)
My_Account = driver.find_element_by_link_text("My Account").click()
time.sleep(1)
Email_address = driver.find_element_by_id("username").send_keys("plis_in@mail.ru")
time.sleep(1)
Password_in = driver.find_element_by_id("password").send_keys("123Qaz456!@#$<>?")
time.sleep(1)
Remember_me = driver.find_element_by_id("rememberme").click()
time.sleep(1)
Register = driver.find_element_by_xpath("//input[@value='Login']").click()
time.sleep(2)
Shop = driver.find_element_by_css_selector("#menu-item-40 > a").click()
time.sleep(1)
HTML = driver.find_element_by_css_selector(".cat-item-19>a").click()
time.sleep(3)
HTML_count = driver.find_elements_by_class_name("product")
if len(HTML_count) == 3:
    print("В категории HTML 3 товара")
else:
    print("Ошибка. Количество товаров в категории HTML: " + str(len(HTML_count)))
driver.quit()